POST http://localhost:5000/api/product
Content-Type: application/json

{
    "bannerImage": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Roblox_Logo.svg/1200px-Roblox_Logo.svg.png",
    "categoryId": 2,
    "code": "ROBUX",
    "description": "Top up Robux untuk Roblox game. Dapatkan Robux instan untuk membeli item, aksesoris, dan fitur premium di Roblox.",
    "isActive": true,
    "name": "Robux",
    "order": 2,
    "slug": "robux",
    "thumbnail": "https://upload.wikimedia.org/wikipedia/commons/thumb/8/83/Roblox_Logo.svg/500px-Roblox_Logo.svg.png",
    "subName": "Roblox Robux"
}

############################
GET http://localhost:5000/api/product?limit=10&offset=0
Content-Type: application/json

############################
GET http://localhost:5000/api/product/search?limit=10&query=Tel
Content-Type: application/json
############################
GET http://localhost:5000/api/product/digiflazz
Content-Type: application/json


############################
PUT http://localhost:5000/api/product/4
Content-Type: application/json

{
    "name": "TEST KEDUA",
    "order": 4,
    "is_active": false,
    "icon": "https:///"
}

############################
DELETE  http://localhost:5000/api/product/6
Content-Type: application/json

