POST http://localhost:5000/api/category
Content-Type: application/json

{
    "name": "Langganan",
    "order": 4,
    "is_active": true,
    "icon": ""
}

############################
GET http://localhost:5000/api/category?limit=10&offset=0
Content-Type: application/json


############################
PUT http://localhost:5000/api/category/1
Content-Type: application/json

{
    "name": "Populer",
    "order": 1,
    "is_active": true,
    "icon": ""
}

############################
DELETE  http://localhost:5000/api/category/6
Content-Type: application/json

