import { TransactionStatus } from "../Transaction/types";
export type OrderInvoice = {
  id: number;
  invoice_number: string;
  status: TransactionStatus;
  product_code: string;
  destination: string;
  amount: number;
  price: number;
  discount: number;
  total: number;
  payment_method: string;
  created_at: string;
  customer_email: string;
  customer_phone: string;
};
export type Order = {
  id: number;
  user_id: number;
  product_code: string;
  provider_id: number;
  reference_id: string;
  invoice_number: string;
  external_id: string;
  status: TransactionStatus;
  payment_method: string;
  payment_code: string;
  payment_url: string | null;
  price: number;
  quantity: number;
  amount: number;
  discount_price: number;
  voucher_code: string;
  fee: number;
  tax: number;
  total: number;
  customer_email: string;
  customer_phone: string;
  destination: string;
  serial_number: string | null;
  log_request: string | null;
  log_response: string | null;
  log_callback: string | null;
  error_message: string | null;
  metadata: string;
  ip_address: string;
  user_agent: string;
  payment_at: string | null;
  expired_at: string | null;
  completed_at: string | null;
  cancelled_at: string | null;
  refunded_at: string | null;
  created_at: string;
  updated_at: string;
};
